spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cartoon
    username: root
    password: rootroot
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  logging:
    path: C://SpringBootLog
    level:
      cn.carbs.backend: debug
      org.springfromework.web: info
      org.hibernate: error
#  mvc:
#    throw-exception-if-no-handler-found: true
    #不要为我们工程中的资源文件建立映射
#  resources:
#    add-mappings: false